### ISSUE TITLE
SPIN_VERSION env var is set by this action

### ISSUE THREAD

**Issue by vdice** [fermyon/actions#65]
As seen [here](https://github.com/search?q=repo%3Afermyon%2Factions%20SPIN_VERSION&type=code), this action sets the `SPIN_VERSION` env var in the action environment.

This means users of this action attempting to supply their own value via an env var of the same name won't be able to do so.

Consider the following:
```
env:
    SPIN_VERSION: v2.4.2
    
jobs:
  myjob:
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          version: ${{ env.SPIN_VERSION }}
```

`env.SPIN_VERSION` will end up resolving to the output of `spin --version` per https://github.com/fermyon/actions/blob/ff08c824f11ad96ae0f8d8ac814df25718579fe4/src/spin.ts#L14.
